version: '3.8'

services:
  sqlmap-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8775:8775"
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "sqlmapapi.py", "-s"]
